### ISSUE TITLE
目前云函数版本，不支持sessionToken验证，如何进行用户验证

### ISSUE THREAD

**Issue by qumeta** [leancloud/csharp-sdk#140]
var currentUser = LCEngineRequestContext.CurrentUser;
这个无效的，我看只有LCClassHookController的hook才做了处理，
这个sdk后边计划支持吗？

**Comment by onerain88** [comment]
因为拉取请求的 User 对象需要和存储模块通信，而这一需求对于开发者来说也不是必须的，所以目前的处理方式是`如果请求中带有 User 数据，则反序列化为 User 对象；否则，则只保留 SessionToken，由开发者自行拉取`。

**Comment by onerain88** [comment]
不过我觉得这是一个好建议，可以提供一个 GetCurrentUser() 的异步方法，由 SDK 封装 User 的查询和缓存。

**Comment by qumeta** [comment]
ok,那目前先关闭了
