### ISSUE TITLE
上传 40+MB 大小文件异常

### ISSUE THREAD

**Issue by onerain88** [leancloud/csharp-sdk#197]
[帖子](https://forum.leancloud.cn/t/net-sdk-document-not-found/25056)
分析原因可能和 Flutter 类似，是因为直传文件导致的，七牛对于大文件需要分片方式

**Comment by weakish** [comment]
七牛的文档是说直传最多支持 1G 文件，按说 40 MB 是可以直传的。当然可能用户的网络不是很好，直传大文件中途失败了。

**Comment by onerain88** [comment]
之前有 flutter 用户反馈 30+MB 就会报错，可以复现

**Comment by onerain88** [comment]
https://github.com/leancloud/csharp-sdk/pull/198
