### ISSUE TITLE
上传图片后，返回的imageURL打开后是{"error":"Document not found"}

### ISSUE THREAD

**Issue by theoractice** [leancloud/csharp-sdk#24]
上传图片后，返回的imageURL打开后是`{"error":"Document not found"}`，不能打开图片

[https://github.com/gpake/qiniu-wxapp-sdk/issues/55](https://github.com/gpake/qiniu-wxapp-sdk/issues/55) 这里说是上传域名问题

**Comment by onerain88** [comment]
我们这版 SDK 还没有公开，请使用[旧版](https://github.com/leancloud/unity-sdk/releases)

**Comment by theoractice** [comment]
原来这里是新的。我用的就是旧版，nuget直接下载的，一样出错。

我看到的原因是`https://*.api.lncld.net/1.1/fileTokens`返回的url是错的。正确的图片url在`https://upload.qiniup.com/mkfile/`返回的key里。用这里返回的key值可以正常获取图片。

**Comment by onerain88** [comment]
粘一下代码

**Comment by theoractice** [comment]
```
        public string LeanCloudFileUpload(string path)
        {
            AVFile file = new AVFile(Path.GetFileName(path), File.OpenRead(path));
            file.SaveAsync(new ProgressListener()).ContinueWith(t =>
            ...
        }
```
我抓包看到有个对七牛的`mkfile`的post请求，从响应里拿到了key，用key加上七牛的域名就可以正确下载图片，说明图片确实是传到七牛上了。

**Comment by theoractice** [comment]
> 粘一下代码

请问问题复现了吗？如何解决？

**Comment by onerain88** [comment]
我刚刚确认了一下，确实有些问题，我修复一下。
感谢反馈！

**Comment by onerain88** [comment]
已经在新版（2019.8.26.1）中修复了此 bug，再次感谢您的反馈！

**Comment by theoractice** [comment]
问题已解决，thx
