### ISSUE TITLE
是否支持.net core? 

### ISSUE THREAD

**Issue by dyangrun** [leancloud/csharp-sdk#42]
刚才.net core 3.1导入release 0.2.0的dll正常，但是运行的时候，调用LCObject.SaveAll 或者直接使用Save 都会出现 Invalid URI: The format of the URI could not be determined. 报错

`此异常最初是在此调用堆栈中引发的:
	System.Uri.CreateThis(string, bool, System.UriKind)
	System.Uri.Uri(string)
	System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
	LeanCloud.Storage.LCObject.SaveBatches(System.Collections.Generic.Stack<LeanCloud.Storage.Internal.Object.LCBatch>)
	System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
	System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
	LeanCloud.Storage.LCObject.SaveAll(System.Collections.Generic.List<LeanCloud.Storage.LCObject>)`

**Comment by dyangrun** [comment]
不是.net core的问题，是因为本来不需要输入服务器地址
我默认以为自己也会使用默认地址造成
，因为没有服务器地址，构建REST API时候会造成url非法

https://github.com/leancloud/csharp-sdk/pull/43

**Comment by onerain88** [comment]
由于政策问题，LeanCloud 服务在国内是「必须使用」自有域名的，而海外是「不强制的」。
SDK 是通用的，所以将这个参数设置为「可选」。
这版 SDK 刚刚发布，有问题欢迎 issue，我这边会及时跟进的。
非常感谢关注。

**Comment by dyangrun** [comment]
> 由于政策问题，LeanCloud 服务在国内是「必须使用」自有域名的，而海外是「不强制的」。
> SDK 是通用的，所以将这个参数设置为「可选」。
> 这版 SDK 刚刚发布，有问题欢迎 issue，我这边会及时跟进的。
> 非常感谢关注。

你可能没理解对我说的意思，服务器地址，构造url的时候用的，默认不输入的情况下，为null，构造REST API的时候格式错误因为没有协议头。
如果是可选和不可选的话，那不应该产生构造错误，而是应该连接到默认服务器吧？
欢迎修改一下你们的test case的，默认输入服务器地址和不输入服务器地址覆盖一下~

**Comment by onerain88** [comment]
嗯，我了解了。
确实这里不应该抛出 url 异常，应该提示用户配置 url。
